### ISSUE TITLE
Question: How to Activate Quick Tabs from Keyboard

### ISSUE THREAD

**Issue by nizdobs** [babyman/quick-tabs-chrome-extension#104]
My apologies if this is addressed in the docs, I didn't see it.

Is there a way to activate QuickTabs from the keyboard so I don't have to use the mouse to click the Chrome toolbar shortcut?

Thanks,

- Niz

**Comment by sinkingshriek** [comment]
Hey @nizdobs, I don't know which version of Chrome implemented this but if you have latest version of Chrome then it should give you options to create your own keyboboard shortcuts under "Extension" tab (at the bottom). This extension used to have default keyboard shortcut but got removed because of that option provided by Chrome leaving up to the user to create their own shortcut instead of clashing with others (atleast that's what I think was the intention).

**Comment by nizdobs** [comment]
This worked perfectly, thank you.

**Comment by babyman** [comment]
Thanks @sinkingshriek =)
