### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by akhakarish** [babyman/quick-tabs-chrome-extension#132]
Great extension, the best, just gave you 5 stars.
I would love to have an option to pop it out as a separate window.

**Comment by fcherman** [comment]
Evan, I also wanted the ability to keep the popup active when I move away from the current tab – so much so that I bookmarked the address of the extension (chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/popup.html). I click on the bookmark to view the popup as a  page in its own tab (see screenshot). The tab stays open if I move to other tabs; unfortunately, it does not stay open if use the extension to navigate to another tab – not even if I "pin" the QuickTabs page. :-(   I realize you designed it to do this (or maybe Chrome requires it), but I would love to be able to keep it open so that if the tab I chose isn't the one I wanted, I can quickly choose another. I think that's probably what the OP also has in mind. Is there any way this could be accomplished – even if it's just a hack I do to my local copy?

Best wishes,

Frances Cherman 

![image](https://cloud.githubusercontent.com/assets/59314/16214332/f9f68686-370b-11e6-9335-fc460970c646.png)
