### ISSUE TITLE
Speed up or eliminate menu animation?

### ISSUE THREAD

**Issue by crispinb** [babyman/quick-tabs-chrome-extension#142]
The question mark's because I don't know what the Chrome extensions API permits in this area. I thought there might be a QuickTabs option to change this, but couldn't see anything.

For me, the animation is just a speed bump. Finding and switching to a current or recent tab is something I'll do many times per day, and speed is of the essence. The menu seems to be populated very fast; it's a shame for its use to be delayed by animation.

**Comment by babyman** [comment]
I know the popup animation really slows down popup and I'm not sure there is any way to change or disable it, the render time of the popup content (32 tabs open) on my 3 year old MacBook Air is:

```
POPUP tab template rendered total time 50 m/s, delta 27 m/s
```

If your interested the log line is in [popup.js](../blob/master/quick-tabs/popup.js#L452), you can temporarily enable debug logging from the background page console by typing:

```js
debug=true
```

I find the quick next/previous tab shortcut keys (unmapped by default) really helpful if you are only switching between a couple of tabs since they do not load the popup window (which can make things a little confusing, but fast)

**Comment by crispinb** [comment]
Right, I suspected it might be a Chrome limitation. For reference:
`POPUP tab template rendered total time 36 m/s, delta 18 m/s` (2013 MB Pro)
That's hardly catastrophic really. UI delays often feel longer than they really are ;)

Thanks also for the next/previous shortcut keys tip, I hadn't come across that.
