### ISSUE TITLE
Lately extension is opening very slowly

### ISSUE THREAD

**Issue by szebrowski** [babyman/quick-tabs-chrome-extension#158]
When I'm using the default keyboard shortcut (ctrl+q) I have to wait ~3s for the extension to show the list. The problem started like 2-3 weeks ago. :(

**Comment by babyman** [comment]
@szebrowski that's strange the code hasn't been updated since September last year... could anything else be causing Chrome to slowdown?

**Comment by szebrowski** [comment]
The slow down is even worse. :(. I will try to do SQLite vacuum.

**Comment by junxy** [comment]
@babyman I guess the reasons may be updated chrome latest version? 
```
chrome 55.0.2883.87 m
Microsoft Windows 10 [Version 10.0.14393]
```

**Comment by babyman** [comment]
Strange, I'm running...

Chrome Version 55.0.2883.95 (64-bit) 
OSX (10.12.2 (16C67)) 

...but I just upgraded my hardware so it's hard for me to notice anything being slow (yet).

@szebrowski did the SQLite vacuum help, any other thoughts?

:|

Evan

**Comment by kcbrown** [comment]
I've found the same thing, though I have a LOT of tabs open (240 for my current session, for instance).  If the issue is with retrieval of the tab list, then Quick Tabs is probably doing it wrong, because Session Buddy has to retrieve the same information, and doesn't take nearly as long.

This needs to work quickly even in the face of numerous open tabs, precisely because its usefulness is primarily when one has a lot of open tabs.  Right now, it's not.

This issue is independent of operating system as well -- it occurs under Linux, Mac OS, and Windows.

**Comment by szebrowski** [comment]
After vacuum it is mostly much better but not perfect. 

Delay of showing up QuickTabs with the keyboard shortcut is random, without changing anything and staying on the same tab: I can press ctrl+q and esc couple of times and sometimes there's no delay and sometimes there's like 2s delay.

Maybe as the previous post states the problem lays in the implementation? :)

**Comment by babyman** [comment]
The extension includes logging for the popup generation time, you can enable this from the background pages JS console by launching it from the extensions list page and entering setDebug(true):

![image](https://cloud.githubusercontent.com/assets/120736/22473869/34072ab8-e7a8-11e6-9dd3-80baf10e3cc4.png)

The popup.js includes a logging timer (popup.js line 84) that logs "tab template rendered" at line 452 once the popup html generation has completed, after that Chrome is managing the render etc.

I can think of 2 issues with this:

1/. my timing code is buggy
2/. the way the html is pushed to Chromes renderer is sub-optimal

If you can enable the debug logging it would be great to see how that looks, please include the number of open tabs at the time.  Any thoughts about performance improvements would be great since sub second rendering is essential for an extension like this!

Thanks,

E

**Comment by jnovak** [comment]
I'm experiencing this as well. Latest Chrome (64-bit) on Ubuntu. How can I vacuum the DB?

**Comment by ryudice** [comment]
I'm having this issue as well. I have about 40 tabs open usually.

**Comment by gazialankus** [comment]
I think, right now the shortcut waits for the list to be populated before showing the popup. So, the user is not allowed to type their search query before the tab list is populated. This is bad, because you just want to hit the shortcut and start typing the name of the tab you want. It's OK if the result comes later, but it's not OK that the user has to wait before typing. 

Perhaps it would be a good idea if the shortcut immediately opens a text field for the user to type in, with a blank tab list below. Later, in time, the list of tabs below could be updated. 

(This is me speculating without looking at the code)

**Comment by boazrymland** [comment]
I love this extension but I have a problem with it being unresponsive.
In my setup I have some 1 second delay. Now, the delay is ok to me - if I was able to type in my search query. But, as a keyboard oriented person like I am, I usually type in the shortcut key then start typing and then hit enter - all of this before the pop up opened, and this results in a google window opening to me, instead of filtering the tabs list and switching.
I think as suggested above, the list can take time to build but inputting some text and hitting enter should not 'resolve' until it has loaded. As it is now, it resolves and runs this google search instead.
