### ISSUE TITLE
Please add an option for the extension to work this way. ( When you have many tabs open! )

### ISSUE THREAD

**Issue by JrsM30** [babyman/quick-tabs-chrome-extension#175]
It would be nice to have an extension option to work this way when you have many open tabs.
 Images 
http://i.imgur.com/ktLHMTj.jpg
http://i.imgur.com/BrOAfBq.jpg
http://i.imgur.com/oWTNiqi.jpg
http://i.imgur.com/kyypos7.jpg

**Comment by JoelAzaria** [comment]
To things friend: 

1.  Your request might get more play if you actually wrote out what you want instead of making ppl click through pictures.  Pictures are great but **say**  (ok, *type*) what you want.

2.  I'm not sure but you might be able to work that out in CSS by constraining the height of the container and letting/making it overflow horizontally.
In the extension's options there is a place to drop custom CSS fyi.
