### ISSUE TITLE
Quick previous tab shortcut sometimes works

### ISSUE THREAD

**Issue by ChiefBK** [babyman/quick-tabs-chrome-extension#192]
This started to occur after I changed this shortcut mapping on laptop A. The extension on Laptop A works as it should and everything was good until I started using laptop B. Chrome synced the shortcut mapping change properly but when I tried using it works about 60% of the time. Laptop A still works like a charm

HOWEVER

I did some debugging and I noticed that if I navigate to a tab -> use cmd-E to open the menu -> close the menu -> than use previous tab shortcut -> it works without fail. 

I've disabled and re-enabled the extension, removed and re-added the extension, restarted chrome, and restarted my computer. 

Google Chrome 61.0.3163.100
Quick Tabs 2017.5.10
OS X El Capitan 10.11.6

**Comment by leedoyle** [comment]
I also have this bug. Previous tab shortcut doesn't work reliably. E.g. just now I visited tab2, then returned to the gibhub tab, then hit the shortcut, and it got me to tab 4. I have yet to find out if the bug also applies to the tab list in the popup.

**Comment by ChiefBK** [comment]
@leedoyle That's seems consistent with what I'm experiencing! I noticed that if I wait a few seconds in the current tab before going to the previous one it works more reliably.

**Comment by contentfree** [comment]
You have to watch for when the color of the icon changes from yellow (I believe) back to its default of dark blue. This lets you switch back through multiple tabs, wait, and then go back to the previous tab. The _wait_ is what registers the current tab as the new "most recent" tab.

It's a little annoying because there's no option to change the delay. (Going to go start a new issue for that option.)
