### ISSUE TITLE
search behaving strangely

### ISSUE THREAD

**Issue by goleary** [babyman/quick-tabs-chrome-extension#217]
![image](https://user-images.githubusercontent.com/16123225/39897530-74035376-5467-11e8-84c5-beb66cb112f6.png)
Here you can see that when I typed rei.com into search the rei.com page didn't show up.  I was able to located it using a word from the page title.

page in question link here: https://www.rei.com/product/115420/scott-supertrac-rc-trail-running-shoes-mens

**Comment by TallTed** [comment]
I have observed a similar issue. When I type a string into the search box, it is (frequently, but not always!) treated as individual letters rather than as a string.

Note the highlighted *letters* in both of @goleary's screencaps -- rather than matching on `rei`, it's matching on `r AND e AND i`; rather than matching on `scott`, it's matching on `s AND c AND o AND t`...  

This is more than counterintuitive, especially since you can't use `"` wrappers to force a whole-string match (because the `"` are then treated as part of the search string, and there would be no match on either `"rei"` or `"scott"`)!

**Comment by dwhly** [comment]
> I have observed a similar issue. When I type a string into the search box, it is (frequently, but not always!) treated as individual letters rather than as a string.

I came here to say the same thing.  I'm sure the goal was to optimize for certain situations (though I'm struggling to understand which).  But the current search behavior makes it quite difficult to find what you want.

If I type "Tom" into the search box, it should find Tom!  Instead it finds the first tab with "T" and "o" and "m" somewhere in the title or URL, which means basically all the tabs *except* the one I'm looking for.  Even more confusingly, it searches the title first and the url second.  So it finds any title where the characters T O and M are present and sequential, starting w/ title first and url second.  Odd!

(Unfortunately it looks like this project isn't actively being maintained.  No updates since October of last year.)

**Comment by JoelAzaria** [comment]
I find this report a little add as that is precisely how I find tabs much of the time (typing the domain or hostname and domain name) and it works for me readily.

Which "search type" do you have selected in the options?  I'm using Fuzzy Search.

Actually, here are all my settings:
![image](https://user-images.githubusercontent.com/470908/44302449-d987a480-a2f6-11e8-8f3a-6b7f1038f669.png)

And here it is in action (sorry for all the redaction but I think the pertinent parts show)
![image](https://user-images.githubusercontent.com/470908/44302505-13a57600-a2f8-11e8-8dbe-be3b1b11c02c.png)

**Comment by dwhly** [comment]
Shame on me. Thank you for these pointers.  All better now.  Should have been a different default?  :)

**Comment by dwhly** [comment]
I think Regex is what I was expecting.

**Comment by TallTed** [comment]
@JoelAzaria - My settings were the same as yours (except the "Always search URLs" was off, which I've now turned on, and seen no change in behavior.)

Your sample screenshot actually shows *exactly the problem* reported, which you can see by looking at the highlighted characters in the result-list.  The second result highlights the **`n`** in "Single Ticket" before moving on to highlight the **`oc.azar`** in the URI (which happens to be the first place those characters appear), where most people would expect it to highlight the **`noc.azar`** in the URI.  If you look at the later results, again you'll see it's finding the pages that have that sequence of characters with any number of characters between...  

If I wrote it in regex, the match would be something like --

    ^.*n.*o.*c.*\..*a.*z.*a.*r.*$

-- would which be put against the concatenation of title+url.

I think it is pure luck that your particular search(es) bring up your desired results at the top.

@babyman - I do not think this behavior is what's *expected* by *any* user, even if it is alluded to by the [TODO writeup of Fuzzy Search](https://github.com/mattyork/fuzzy#todo) (which says they want to make it behave more like the expectation I described above).

Substring is what most humans will expect as the default.

RegEx as default isn't crazy, as it's fairly common (and many search strings will have the same effect with regex as with substring).

I don't understand the [documentation of Fuse Search](http://fusejs.io/) at all, probably because I'm not a coder, so will not comment on it.

**Comment by TallTed** [comment]
@JoelAzaria - You might try searching on some other strings, like `like` or `necktie` and see what comes up. Then perhaps you'll understand what we're getting at.

**Comment by JoelAzaria** [comment]
@TallTed  So I tried your suggestions and I'm really not sure what you meant for me to see.  
I guess I really am missing the issue here but I think that's not important.  I'm not trying to discredit or negate your claim there's a problem.  I was trying to understand it and when I failed to, just thought I'd add another data point in case it helps you to figure it out.   

I expect it's just down to use cases and I don't really use it in a way that bumps up against this issue/limit.  Sorry can't help more.
Again, gl getting resolved.

**Comment by alon91** [comment]
The extension seems promising, but like others in this bug I find the search results absolutely baffling.

I experience the same gap in user expectations as @TallTed and @goleary: the search is on individual characters rather than entire words / substrings. 

@JoelAzaria: I think one possible disconnect here is that you appear to be concerned with searching URLs (specifically domains) and I only want to search _bookmark names_. In settings I've turned off both 'Show URLs' and 'Always search URLs (even when not shown)'.

This means that when I search for 'ahr notes' I get:

- First search results: DoubleClick Se**a**rc**h** collate**r**al li**n**ks + n**otes** ds3
- Second search result: **A**ccount **H**ealth **R**eport (AHR) **notes** + links


My _expectation_ is for this extension to search for the entire term 'AHR' and the entire term 'notes', not individual characters. I would never expect the first search result to appear.

I'll note that I've tried all four search options and none of them match my expectations -- 'Perform Substring Search (exact string matching search)' comes closest but doesn't match when words aren't in the exact order.

For a similar extension that matches my expectation for search results you can check [Popup my Bookmarks](https://chrome.google.com/webstore/detail/popup-my-bookmarks/mppflflkbbafeopeoeigkbbdjdbeifni).

**Comment by JoelAzaria** [comment]
@alon91 Thanks for the perspective, our use cases not only differ they're polar opposites.  I ONLY ever want to find on open tab or url.  I NEVER EVER search a bookmark.  I've turned off every option I found that even hinted at searching bookmarks.
 
So yeah, use case.   I assume you've tried all 4 search types (see screenshots in my first post)?

Hope this gets resolved for you all.  Having search that finds everything BUT what you're looking for has to suck big time.  Wish I had more to offer.

**Comment by MartinLichtblau** [comment]
I investigated the issue since I understand your concerns. 
First clarify that the highlighted single characters aren't the problem here. To find your rei.com example just use fuse as search-algo. 
Furthermore I did some changes to improve the user experience IMO:

**Comment by TallTed** [comment]
@MartinLichtblau -- 

It appears that your Option 1 and Option 2 are orthogonal concerns, and hopefully both will be implemented/active (and/or choosable options) in the new version?

As with @JoelAzaria -- Assuming rollback is easy, and it's not going to mess with anything else I'm running, I'm happy to try the update.

**Comment by MartinLichtblau** [comment]
Here you go: https://drive.google.com/open?id=1vzG3gLA9xvSopgnCaVd7AB5fJr8AeeAQ
Steps to use:

**Comment by MartinLichtblau** [comment]
@TallTed Thx for the feedback — will implement. To me it also seems that Fuse-Letters/default works best.
@JoelAzaria You are right and the Fuse fails at explaining the tokenize and matchAll options. 

I'll try it out for a while and see whether I find any unexpected search behavior like before. Until then I won't do a pull-request, change version or UI. In ~two weeks I'll return. Until then: 
1. here is a new version: Multiple-Words mode better UXP by showing only more accurate results.
2. I would reduce the number of fuse search modes to two or even one. With this version I prefer the multiple-word based mode. 
Old link to new version > https://drive.google.com/open?id=1vzG3gLA9xvSopgnCaVd7AB5fJr8AeeAQ

**Comment by JoelAzaria** [comment]
@MartinLichtblau trying the new version.  On your rec I'm changing from Fuzzy to Fuse 'Multiple Word'.  Will see how it goes and report back.

For the record the previous unpack from 8 days ago has been working for me w/o incident.

**Comment by babyman** [comment]
Hey All,

I see you all working hard on the search code and wanted to say thanks.  If you want to submit a pull request when you have the time I will take a look and fold the changes into the released version.

Happy new year :)

Evan

**Comment by JoelAzaria** [comment]
MartinLichtblau is doing all the hard work, I'm just along for the ride :)

@MartinLichtblau fwiw I've had no issues.  I did change to fuse and even though it picks up disparate items it definitely hits the better results first and higher.  Fuzzy fit my use case correctly but set like this Fuse is perfectly usable for me and I may actually just leave it.

So a) thank you.
b) consider a pull request.  Working well here.  

@TallTed - thoughts?

**Comment by MartinLichtblau** [comment]
Thanks for feedback! Made a PR, with small changes. UI intergrations is unsatisfying, but keeps code simple.

**Comment by MartinLichtblau** [comment]
And since I'm already on. I made another PR to make highlights more relevant by removing short matches. I think this belongs here, since initially the issue started with the mentioning of this irritating behavior. What do you think about [highlighting only longer ~ more relevant matches](https://github.com/babyman/quick-tabs-chrome-extension/pull/241/commits/28e2792ab409ed1cdeecda96173c344c987dfaa1)?

**Comment by TallTed** [comment]
@MartinLichtblau -- Longer, more-relevant matches are *definitely* desirable.  No matter what the "Search Type", I can think of no scenario where it would make sense to input a search string of "fred" and get a match of "di**f**fe**re**nt ba**d**ges" whether or not I also got a (superior) match of **"fred** jones".

**Comment by JoelAzaria** [comment]
If I understood the question @MartinLichtblau, I think that all matches should be highlighted as long as the longer more relevant are presented first.  
I feel that in @TallTed's example "di**f**fe**re**nt ba**d**ges" _should_ be returned if that's what Fuse returns but only below better matches like "fred jones".

Since part of the function/advantage of Fuse is to find "close enough" matches when you don't spell smth right, etc, I wouldn't encourage excluding them, but certainly they should be de-prioritized with the better/more relevant results coming out higher.

**Comment by MartinLichtblau** [comment]
@TallTed I agree with you, although I am not entirely certain. 
@JoelAzaria No, I don't think so. It seems you misunderstood: the text highlighting has nothing to do with showing the tabs in the result list; totally independent. 

I go even further and say: highlights are useless to identify the right tab. I mean how many tabs do you have? Do you really decide based on the highlights?   I look on the icon and the text and instantly know if it's the one I'm looking for. Highlights just clutter the view, distract and overall slow down. 
A less radical approach is to make highlighting optional or to change the way it is done. An alternative highlighting method could look sth. like: 
-  `minMatchCharLength: findShortestWord(query).length - 1` highlight only matches > length of shortest word in query (-1 ico typos)
- `minMatchCharLength = findShortestWord(query).length / 2` highlight only matches > half the length of shortest word in query

But with the new fuse search the right result is anyway at the top; no need to highlight :-D

**Comment by JoelAzaria** [comment]
@MartinLichtblau so you're just talking about highlighting the "matched" parts of the search... ok.

but saying 
> "highlights are useless to identify the right tab"
I can't agree with that.

For one, it does serve to inform how the search concluded that a match is relevant, which is better than wondering "HowTF did THIS result make it in here?".  

> "Do you really decide based on the highlights?"

I'd say (confess?) that I use the highlighting specifically to draw my eye to the relevant portions in the results.  I have gone so far as to find custom CSS and then customized it further to ensure good color choices and contrasts that work for me for just that reason.

> "I mean how many tabs do you have?  

I can be running with MANY open tabs and can return large handfuls of results. 50-80 tabs over a dozen or two windows is not uncommon (somtimes more but Chrome leaks like a sieve.)  QT results of one or two to a dozen or more also not uncommon.  And that is where highlight and good color choice plays for me.

Wrt your example, I am sorry but can't interpret the code to a visual, so I'm nos sure what to "see" there.  Hopefully I've understood enough and my explanation is clear.

**Comment by TallTed** [comment]
Because this question has come up... 

I have 481 open Chrome tabs right now.  Several thousand more pages are in my History.

The favicon *helps*, but is far from sufficient, to know which tab I'm looking for in the list.  Even the displayed page-title and URI aren't always enough on their own, because they're both truncated.

I just experienced a typo search ("girhub") with Fuse + Multiple Words, and got this in my results --

<img width="378" alt="screen shot 2019-01-10 at 03 56 58 pm" src="https://user-images.githubusercontent.com/2559602/50996627-69b9c680-14f0-11e9-9cbb-68703d9bb951.png">

> search behaving strangely • Issue #217 • babym...
> **h**ttps://g**i**t**hub**.com/**b**a**b**yman/q**ui**ck-ta**b**s-c**hr**ome-extens**i**on/**i**s...

**Comment by babyman** [comment]
I have packaged and uploaded the merged code to the Chrome Store, it will take a few hours to release but you should see something in the next day or so.

Thanks again everyone.

**Comment by JoelAzaria** [comment]
Thank you @babyman and thank YOU @MartinLichtblau for the improvements.  

Thanks all :)

        . ,                
         *                              
    ` *~.|,~* '   
    '  ,~*~~* `     _            
     ,* / \`* '    //                  
      ,* ; \,O.   //      
          ,(:::)=//    
         (  `~(###)             
          %---'`"y                     
           \    /
            \  /            
           __)(__                       
          '------`

**Comment by MartinLichtblau** [comment]
@JoelAzaria thank you so much for your effort describing how you use Quick Tabs — so insightful for me! And also @TallTed : wow, so many tabs... 

@all Thanks to TallTed's screenshot I just realized that Fuse word-based doesn't highlight as expected and this is likely due to a [bug in fuse](https://github.com/krisk/Fuse/issues/265). But, I would wait until it's fixed in fuse.  

And concerning highlighting of matches: See for yourself by trying it out > https://drive.google.com/open?id=1vzG3gLA9xvSopgnCaVd7AB5fJr8AeeAQ
