### ISSUE TITLE
How to open the popup to search from Keyboard ??

### ISSUE THREAD

**Issue by aditya777hp** [babyman/quick-tabs-chrome-extension#227]
I want to know the keyboard shortcut through which i can search for the list of open tabs using only the keyboard.
I press ctrl +e then it takes me to the address bar!!!
and i do not want to mess with chrome's default shortcuts
Win10 user here !!

**Comment by JoelAzaria** [comment]
QT's shortcuts are set up and managed by Chrome.  That's Chrome's choice for ALL extensions now.
Go here: chrome://extensions/shortcuts
Find QT.  Set shortcuts you want.  Prosper.

![image](https://user-images.githubusercontent.com/470908/45049295-30f27800-b04c-11e8-859f-b45d4ceaa0b3.png)

I use ctrl+sh+q.  You may not want to use that because it overlaps Chromes "close all windows" shortcut.  I have multiple Chrome profiles and ones that DONT USE quicktabs I sometimes screw myself and close all windows out.
Just choose a shortcut that Chrome doesn't use elsewhere and you'll be fine.  Can also change it anytime you want if you later find problmes.

**Comment by aditya777hp** [comment]
Its a whole new World !!! 
Thanks
