### ISSUE TITLE
Prev/Next hotkeys

### ISSUE THREAD

**Issue by Allasso** [babyman/quick-tabs-chrome-extension#229]
Hi,

Either the quick-prev/quick-next hotkey implementation is buggy as all getout, or I just can't make any logical sense out of it.  They don't seem to follow the order listed on the menu, nor when carefully noting the order of tabs I've visited, don't follow that either.  At times the keys don't work at all, even though it seems I should not be at either end of the history.  Any comments on this?

Also, I notice in the manifest that

    "quick-prev-tab": {
      "description": "Quick next tab

    "quick-next-tab": {
      "description": "Quick prev tab

Note, names and descriptions are reversed, although I don't think this would affect the experience I am having with them.

Thanks.

**Comment by Allasso** [comment]
I notice this issue has been closed.  I'd just like to note that the work being done in 
 [5c7f796](/babyman/quick-tabs-chrome-extension/commit/5c7f796d3f3dd55d8901f966ce174a6a0abdaf83) does not address the first part of the O.P.

**Comment by MartinLichtblau** [comment]
> 1. Either the quick-prev/quick-next hotkey implementation is buggy as all getout, or I just can't make any logical sense out of it. 
1.1 They don't seem to follow the order listed on the menu,
1.2 nor when carefully noting the order of tabs I've visited, don't follow that either. 
> 2. At times the keys don't work at all, even though it seems I should not be at either end of the history. Any comments on this?

So 2. is fixed, but not 1., including 1.1. and 1.2? Concerning 1.2.: because of the delay it's hard to intuitively realize which tab is saved as visited or not, although the popup indicates that.
