### ISSUE TITLE
feature request: control + n, control + p to move selector up and down

### ISSUE THREAD

**Issue by etmoore** [babyman/quick-tabs-chrome-extension#230]
When using the extension (on a mac), I'd like to be able to use control + p and control + n to move the selector up and down respectively. I realize it's a fiddly request 😊 , but it's a common hotkey combination that works in many other apps/contexts (eg the Chrome location bar, text editors, bash) and lets me keep my hands on the keyboard rather than having to reach for the arrow keys.

**Comment by JoelAzaria** [comment]
Since this is so specific perhaps the better/wider-use feature request would be "can we have access to set our own hot key for moving selector up and down"

That way you could set it to what you want, the 80-90% of users could leave it (probably) as-is and anyone else with any other edge-case could set it to whatever they may want.

**Comment by etmoore** [comment]
Just realized you can set this preference via: chrome://extensions/shortcuts 🎉 
![image](https://user-images.githubusercontent.com/3310531/47055885-b018b700-d187-11e8-8be5-5af24eacc384.png)

**Comment by JoelAzaria** [comment]
If I'd had a bit more sense (or a bigger cup of coffee) I might have checked that before I replied...

Glad it's worked out for you
