### ISSUE TITLE
Future ownership of Quick Tabs

### ISSUE THREAD

**Issue by MartinLichtblau** [babyman/quick-tabs-chrome-extension#231]
Did anyone hear from @babyman  lately? I haven't, but would like to see this project continue. But without the repository owner we can't do anything. I find it strange that he haven't said anything on here or anywhere else; not on his website, on twitter and so on.
So I contacted @babyman on [twitter](https://twitter.com/babyman) and wait for an answer. In the meantime we could collect ideas on how to proceed if he doesn't reply.

**Comment by babyman** [comment]
Hey @MartinLichtblau I have been really busy the last while and... anyway no excuses!  Time is starting to open up for me to review and merge pull requests, gather the best ideas and fix issues people have been experiencing.  I can't believe it's over a year since the last release!!

Thank you, and everyone else for taking the time to report issues and generally care about this project, I do still use it myself daily so it's far from dead.

Evan
