### ISSUE TITLE
 search string as URL with ctrl + return

### ISSUE THREAD

**Issue by vfxturjo** [babyman/quick-tabs-chrome-extension#264]
hi.
i want quick-tabs to do a google SEARCH with the string written... not the string as the URL.
there is an option for using search string as URL in options page.
![image](https://user-images.githubusercontent.com/44445014/55292619-de751080-540e-11e9-850a-4932c3ad87d7.png)

but if i could google search string with ctrl + return, it would be a lot more helpful.
![image](https://user-images.githubusercontent.com/44445014/55292625-edf45980-540e-11e9-957a-5d199194f9c6.png)
this option with a dadicated shortcut...

please add this feature

**Comment by MartinLichtblau** [comment]
But the second image shows the base url + the search term, which is how you can search on google. So what is missing?

**Comment by alanlgardner** [comment]
I agree with this. After navigating to existing tabs and bookmarks, the next most common action is trying to do a google search (ideally with google search autocomplete). I think the most ideal would be to just open up a new tab and prefill the text in the omnibar with what has been typed so far.

**Comment by MartinLichtblau** [comment]
Two options: 
1. directly search using a custom search engine 
2. just open new tab with the string (search term) in the addressbar which would use the browsers default search engine.

**Comment by vfxturjo** [comment]
Thank you so much for replying!!!!!

Maybe i could not express myself properly.
I am not much good in English but i will try it again...

At first, i will tell you general workflow (so it will be easier to differentiate):
1. Suppose i am watching a video on YouTube.
2. Suddenly i want to search Google "how to cure sore throats" in a new tab.
3. So i will make a new tab, type "how to cure sore throats" in URL bar, then press enter to search.


Now I will tell you a workflow, that i want to do with Quick-tabs.
1. Suppose, i am now watching a video on YouTube.
2. Suddenly i want to search "how to cure sure throats" in a new tab.
3. I press my shortcut to launch quick-tabs.
4. Type "how to cure sore throats" in quick-tabs. And i press ctrl+enter (or any other shortcut set by user)
5. New tab will be opened and "how to cure sore throats" is searched in Google.

The second workflow is not currently possible to do with Quick-tabs.
It is possible only when there are no history/bookmarks related to my search term. Only Then Quick-tabs makes a Google search, otherwise not.
But i want to set a dedicated keyboard shortcut so i can query anything with dedicated shortcut whether similar thing is in my history or not.

TL.DR 
Please make an option to do Google search, instead of using string as URL.

**Comment by MartinLichtblau** [comment]
@vfxturjo Thank you so much for your insightful scenarios! Such a feature can be easily integrated. Well, better say, it is already part of quicktabs and would just need a little change. 

Your scenarios helped me understand and I now know all to well what you mean, since I find myself in such situations all to often. And so I know that any browser including Chrome have shortcuts  to do sth. like this very fast: 
- (option 1): 1. ctrl+t 2. directly type your search 3. if you want to return to previous tab you can use quicktabs.
- (option 2): 1. ctrl+l 2. type your search 3. press Alt+Enter or Ctrl+Enter 4. if you want to return to previous tab you can use quicktabs. 
I use option 2 since it opens the new  tab with search results much faster (and I also created a macro for searching the selected text like this with a single shortcut).

So I'm curious: why you need such a feature if it's already part of your browser itself? :-D
