### ISSUE TITLE
[Bug] - 1st tab gets focused after switching tabs

### ISSUE THREAD

**Issue by avalanche1** [babyman/quick-tabs-chrome-extension#273]
After I've switched to another tab via the means of this extension, in my browser the 1st tab gets the focus, which is very annoying. By focus I mean the element switching selection rectangle you get when press tab repeatedly.
![image](https://user-images.githubusercontent.com/10534563/57288882-0832ee80-70c3-11e9-9212-5e2a0a1b2ba0.png)
I run chrome 73 on os x

**Comment by avalanche1** [comment]
Now, let's say I've switched to a youtube tab with a paused video. I press space to continue watching, but instead I get the 1st tab activated!

**Comment by yanbodiaoweng** [comment]
+1

**Comment by fwextensions** [comment]
Interestingly, the same bug was reported on my [QuicKey](https://chrome.google.com/webstore/detail/quickey-–-the-quick-tab-s/ldlghkoiihaelfnggonhjnfiabmaficg) tab-manager extension.  Something about how macOS and/or Chrome handled tab focusing changed back then.  I was never able to repro it in 10.12, but it seems to affect newer versions.  

I believe the issue is here: https://github.com/babyman/quick-tabs-chrome-extension/blob/master/quick-tabs/background.js#L495

I fixed it by focusing the window before focusing the tab, the opposite of the code in that file.

**Comment by h0tk3y** [comment]
+1, it's especially annoying when using a keyboard-centric control scheme (e.g. Vimium) and not being able to control the page after a tab switch.

**Comment by babyman** [comment]
I just pushed an updated version to fix this issue.
