### ISSUE TITLE
Examples of how to use various search types

### ISSUE THREAD

**Issue by superclarkk** [babyman/quick-tabs-chrome-extension#320]
Even though there was no answer to #204, it was closed.

Again, can someone provide _some examples_?

--------------------------------
Great extension, btw!

It would be useful to have some examples of how to use the various search types, including how to pass options to them to change their behaviour, and what the difference is between them and their benefits.

For instance, personally, I'd like a way to include and exclude search terms, but have no idea if it's possible with any of the search types:

The words "Jack" AND "Jill" in any order (exclude pages that don't include them both)
The word "Jack" but NOT "Jill" in any order

**Comment by babyman** [comment]
@superclarkk thanks for taking the time to repost.

You can try the different search options without changing your preferences by prefixing the query

- `/fuzzy <query>` - use the fuzzy search engine for this query only
- `/fuse <query>` - use the fuse search engine for this query only
- `/regex <query>` - use the regex search engine for this query only
- `/subs <query>` - use the subs search engine for this query only

The first 2 search options, fuzzy and fuse are both variants of fuzzy searching, they will take a search string and score each of the possible results and return them in order, the details of how each works are explained on their respective websites (https://github.com/mattyork/fuzzy and https://fusejs.io/).  Internally they work differently and support for both was added after some discussion about how the fuzzy implementation scored its results, you can read more here #217.

```
/fuzzy jackjill
/fuse jackjill
/fuse jilljack
```

Fuse will find results in both cases but fuzzy will not due to implementation differences.

The third search option, RegEx performs a regular expression match against the tabs, this can likely support the examples you provide to some degree but not in any succinct way.

For example "Jack" AND "Jill" in any order

```
/regex jill.*jack|jack.*jill
```

This stack overflow post discusses multiple word matches in regex https://stackoverflow.com/questions/4389644/regex-to-match-string-containing-two-names-in-any-order#4389683.  Regular expressions are powerful but get verbose quickly, not something that I would typically type to move between tabs.

You might be able to write a regex that matches on  "Jack" but NOT "Jill" in any order but it would likely be extremely unwieldy and may not work when searching tab titles and tab urls.

The final search option searches tabs for exact string matches, nothing fancy but very helpful if you know precisely what you want.

Personally I use `fuse` and find it will quickly bring the tab I'm looking for into the top 2 or 3 results, from there I select it using the arrow keys if necessary.

Hope this helps,

Evan

**Comment by superclarkk** [comment]
Evan

Thank you for such a beautifully-comprehensive answer.  In retrospect, and in reality, I don't imagine that it would be often necessary to use a logical NOT operator and, as you suggest, regex works well for a logical AND (eg `/regex youtube|twitter`). 

I wasn't aware that you could pass the search type as a prefix to the query, but I did look at the Search Type section in the extension's settings when trying to solve my problem. It may be helpful to people if there was a note under the Search Type section that mentions it. Can I raise this as a feature request?

**Comment by babyman** [comment]
I'm glad that was helpful, please do open a ticket to update the search type section, the whole preferences page could use an overhaul!
