### ISSUE TITLE
Number of Tabs Shown + Tab Order Options

### ISSUE THREAD

**Issue by BramJacob** [babyman/quick-tabs-chrome-extension#73]
Would like to request the following two features:

1. Option to show all open tabs, instead of max 25. Popup window would stay the same size, but scrolling down the window would reveal all open tabs.

2. Option to change order of tabs listed by: 
-Current order (left to right)
-Date Created/Opened (if possible)
-Alphabetized (Name of Tab/Title of Tab) - This option used with an extension such as [RenameTab](https://chrome.google.com/webstore/detail/renametab/mkailnbloeepkajmoblllhhhckpbbncg) would allow great amounts of organization.

**Comment by babyman** [comment]
Hi,

I'm not sure I understand these feature requests since:

1/. The popup window does show all the tabs that are open and will scroll if required.

2/. from the features list "tabs are listed in most recently used (MRU) order" but obviously when initially launched the tabs are listed in the order the Chrome API returns them in.

Evan
