### ISSUE TITLE
Option to use old style and ignore bookmarks

### ISSUE THREAD

**Issue by MInner** [babyman/quick-tabs-chrome-extension#75]
Hi, 
extension is great, but today's release style is totally unusable, imho :( 

Could you please give an option to turn those new features off (style and auto bookmark search) because they disturb really much :(

Thanks,
Ben

**Comment by babyman** [comment]
Hey Ben,

Thanks for taking the time to log this, I have been noticing that it's slow when you have a lot of bookmarks and tabs open, I will take a look  into options to improve the render and search speed, sorry for any inconvenience.

Evan

**Comment by xipx** [comment]
Agree with MInner. 
But I like the new UI a lot.
The problem is icons(favicon) is too large.Some website only has a 16×16 pixel favicon, so the whole search list is like a blurry icon farm which is not good. Maybe smaller icon-size is better.

**Comment by babyman** [comment]
I think in the short term I am going to tighten up the UI so that it is a more compact and remove the bookmarks from the popup, I really like the ability to search them but rendering them all makes the UI too slow and unwieldy so I will try to workout a better way to integrate the two.

Evan

**Comment by babyman** [comment]
I just pushed a new version so you should get the upgrade later today, this has a tighter UI and is MUCH faster (on my system 5-10 m/s to render moderate tab list rather than up to 100 m/s).  I have rebuilt the search is it is faster and will include bookmark results if only a few tabs match or if you start the search string with spaces (1 to include bookmarks, 2 will only search bookmarks).

Let me know what you think, your feedback really is appreciated...

Evan

**Comment by MInner** [comment]
Yeah, that look and feels great now, thanks a lot :)

**Comment by xipx** [comment]
Much much better! Great work!

**Comment by babyman** [comment]
Thanks guys, always happy for the feedback.
