### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by MInner** [babyman/quick-tabs-chrome-extension#87]
It seems like there's a memory leak in the extension. After a while (3-4h, >50 tabs opened) it starts consuming up to 700Mb of RAM, I reload it and it start functioning fine. 

Chrome 40.0.2214.111
Ubuntu

Tell me if (how? link?) I can collect and send you it's ram usage profile.

(The extension itself is totally awesome!)

**Comment by babyman** [comment]
That's a bit worrying, I will see how best to track it down and fix it

**Comment by babyman** [comment]
Looks like this might be caused by a GC bug in Chrome, https://code.google.com/p/chromium/issues/detail?id=441500.  The ticket says it was merged into Chrome 2311, hopefully if you update Chrome you shouldn't see this issue any longer, of course if you do I will look into this further =)

I'm running Version 42.0.2311.152 (64-bit) on a Mac.
