### ISSUE TITLE
Shortcut to open Search Bar

### ISSUE THREAD

**Issue by zuernBernhard** [babyman/quick-tabs-chrome-extension#88]
As this Plugin is inspired by IntelliJ I would love to open the search box by Double Shift (Search Everywhere).
Is that possible Somehow ?

**Comment by babyman** [comment]
It's possible to do but not very reliably because you have to inject JavaScript into each of the tabs and then listen for keystrokes using that script.  I used this before Chrome added proper extension key support.

The problem with this approach is that lots of things can capture keystrokes and prevent them propagating to the extension, the other issue is Chrome pages like the extensions page, settings etc do not allow script injection :(

**Comment by zuernBernhard** [comment]
Hm, I just changed to Lines in the Manifest and it works like a Charm. Sadly Commands for Chrome-Extensions have to Consist of Ctrl or Alt so my Keystroke is not Double Shift but Alt+Shift+F

Here is a Pull-Request showing it: https://github.com/babyman/quick-tabs-chrome-extension/pull/89 ...zuernBernhard:master

**Comment by babyman** [comment]
Ahh, I misunderstood, you can change the shortcut key for Quick Tabs by using the "keyboard shortcuts" options at the bottom of the extensions page (chrome://extensions/)

![screen shot 2015-05-14 at 8 18 54 am](https://cloud.githubusercontent.com/assets/120736/7631638/ca730452-fa12-11e4-958e-c73ad36b1de3.png)

But unfortunately Chrome does not have the flexibility of IntelliJ so the only way to support things like double shift involves some pretty unreliable hackery :|
